name: Wails build

on: [push, pull_request]
#on:
#  push:
#    tags:
#      - "v*"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: biliShareMail_linux_amd64, platform: linux/amd64, os: ubuntu-latest},
          {name: biliShareMail_windows_amd64, platform: windows/amd64, os: windows-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install pnpm
        run: |
          npm install -g pnpm
      - uses: dAppServer/wails-build-action@v2.2
        with:
          node-version: 18.x
          build-name: ${{ matrix.build.name }}_${{ github.ref_name }}
          build-platform: ${{ matrix.build.platform }}
