name: Build GUI.for.SingBox

on:
  push:
    tags:
      - "v*"

jobs:
  Build:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        build:
          - os: windows-latest
            GOOS: windows
            GOARCH: amd64
          #          - os: windows-latest
          #            GOOS: windows
          #            GOARCH: arm64
          #          - os: windows-latest
          #            GOOS: windows
          #            GOARCH: 386
          - os: macos-latest
            GOOS: darwin
            GOARCH: amd64
          - os: macos-latest
            GOOS: darwin
            GOARCH: arm64
          #          - os: ubuntu-latest
          #            GOOS: linux
          #            GOARCH: amd64
          # - os: ubuntu-latest
          #   GOOS: linux
          #   GOARCH: arm64
    runs-on: ${{ matrix.build.os }}
    env:
      APP_NAME: BiliShareMall
      ZIP_FILE: BiliShareMall-${{ matrix.build.GOOS }}-${{ matrix.build.GOARCH }}.zip
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: go version
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm -v
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml
      - run: node -v
      - name: Install dependencies
        run: |
          cd frontend && pnpm install
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      #      # Dependencies: GNU/Linux
      #      - name: Update system and dependencies
      #        if: runner.os == 'Linux'
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      # Hide dock bar icon: macOS
      - name: Update system and dependencies
        if: runner.os == 'macOS'
        run: |
          go mod vendor
          sed -i "" "s/\[NSApp setActivationPolicy:NSApplicationActivationPolicyRegular\]/[NSApp setActivationPolicy:NSApplicationActivationPolicyAccessory]/g" vendor/github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin/AppDelegate.m

      - name: Build Frontend
        run: cd frontend && pnpm build

      # Build windows
      - name: Build for ${{ matrix.build.GOOS }}-${{ matrix.build.GOARCH }}
        if: runner.os == 'windows'
        env:
          GOOS: ${{ matrix.build.GOOS }}
          GOARCH: ${{ matrix.build.GOARCH }}
        run: ~/go/bin/wails build -m -s -trimpath -skipbindings -devtools -nsis -tags fts5 -o ${{ env.APP_NAME }}.exe

      # Build macos
      - name: Build for ${{ matrix.build.GOOS }}-${{ matrix.build.GOARCH }}
        if: runner.os == 'macOS'
        env:
          GOOS: ${{ matrix.build.GOOS }}
          GOARCH: ${{ matrix.build.GOARCH }}
        run: ~/go/bin/wails build -m -s -trimpath -skipbindings -devtools -tags fts5 -o ${{ env.APP_NAME }}.exe

      # Compress: macOS
      - name: Create a compressed file for macOS
        if: runner.os == 'macOS'
        run: |
          cd ./build/bin
          # The compiled product name of macos is always "${{ env.APP_NAME }}.app"
          cp -r ../../dict/ ${{ env.APP_NAME }}.app/Contents/MacOS/dict
          zip -q -r ${{ env.ZIP_FILE }} ${{ env.APP_NAME }}.app

      # Compress: Windows
      - name: Create a compressed file for Windows
        if: runner.os == 'Windows'
        run: |
          cd ./build/bin
          Compress-Archive -Path ${{ env.APP_NAME }}-${{ matrix.build.GOARCH }}-installer.exe -DestinationPath ${{ env.ZIP_FILE }}

      #      # Compress: GNU/Linux
      #      - name: Create a compressed file for GNU/Linux
      #        if: runner.os == 'Linux'
      #        run: |
      #          cd ./build/bin
      #          mv ${{ env.APP_NAME }}.exe ${{ env.APP_NAME }}
      #          zip ${{ env.ZIP_FILE }} ${{ env.APP_NAME }}

      # Artifact
      # - name: Upload Artifact ${{ env.ZIP_FILE }}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ env.ZIP_FILE }}
      #     path: ./build/bin/${{ env.ZIP_FILE }}

      - name: Create Release and Upload Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/bin/${{ env.ZIP_FILE }}
          asset_name: ${{ env.ZIP_FILE }}
          tag: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          overwrite: true
          draft: false
          prerelease: false
          body: |
            ## Changes
            ## 安装
            ### MacOS安装
            
            双击压缩文件，将解压后的文件移动到桌面（必须），按照以下步骤操作：
            
            双击可执行文件，出现错误提示“无法打开...因为开发者无法验证”，点击“取消”按钮；
            进入系统设置 - 隐私与安全 - 安全性，找到“无法打开，因为开发者无法验证”，点击“仍然打开”，输入密码确认。
            > 注意：
            > 解压后的可执行文件必须至少移动一次（如上面示例步骤，将其从下载文件夹移动到桌面），否则该可执行文件将没有写入权限。
