name: Wails build

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          { name: BiliShareMall_windows_amd64, platform: windows/amd64, os: windows-latest,end: ".exe" }
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install pnpm
        run: |
          npm install -g pnpm
      - uses: dAppServer/wails-build-action@869d13b213afde171d7223ee5cb31a7b313d15a3
        with:
          node-version: 18.x
          build-name: ${{ matrix.build.name }}_${{ github.ref_name }}${{ matrix.build.end }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          build-tags: fts5
          wails-version: v2.9.1


